import './globals.css';
import type { Metadata } from 'next';
import NavBar from '../components/NavBar';
import Footer from '../components/Footer'; // Use default import without curly braces

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
